version: '3'
services:
  back: 
    build: 
      context: "./back"
      dockerfile: dockerfile 
    container_name: "back" 
    working_dir: "/app/back" 
    ports: 
      - "5001:5001"
    links: 
      - "noderedis"
  front: 
    build: 
      context: "./front"
      dockerfile: dockerfile 
    container_name: "front" 
    working_dir: "/app/front" 
    ports: 
      - "3000:3000"
  noderedis: 
    image: "redis:3"
    container_name: "noderedis"
